### ISSUE TITLE
NuGet complains about packages.config in Visual Studio

### ISSUE THREAD

**Issue by arangas** [tamasflamich/effort#20]
I'm unable to build the solution because NuGet complains about duplicate EntityFramework entries in packages.config for the Effort.Test and Effort.Test.Data projects. I commented out the version I didn't want and it builds but I'm not certain this will break something else if I submit a PR for it. Tested in VS2015.

**Comment by tamasflamich** [comment]
Thanks for reporting this. The project supports both pre EF6 and EF6 libraries. It is done in a tricky way that there is no need for having multiple projects for each EF library. In order to make the package restore process smooth, multiple versions are included in the `package.json`. This wasn't a problem with other versions of VS, but it seems i will need to check VS15.

**Comment by tamasflamich** [comment]
Oh, for some reason I didn't realise that this was fixed. Thank you again.
